baseURL = 'https://www.ionutciuta.com'
languageCode = 'en-us'
title = 'Ionut Ciuta says: hi ğŸ‘‹ğŸ»'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Ionut Ciuta"
  headline = "Software engineer, based in Romania."
  image = "img/avatar.jpg"  # path relative to static directory

  links = [
    { email = "mailto:ionutciuta24@gmail.com" },
    # { link = "https://link-to-some-website.com/" },
    # { dev = "https://dev.to/username" },
    # { facebook = "https://facebook.com/username" },
    { github = "https://github.com/IonutCiuta" },
    { goodreads = { href="https://www.goodreads.com/johnofardeal", text="Goodreads" } },
    # { gitlab = "https://gitlab.com/username" },
    # { instagram = "https://instagram.com/johnofardeal" },
    { linkedin = "https://linkedin.com/in/ionutciuta" },
    { strava = { href="https://www.strava.com/athletes/johnofardeal", text="Strava" } },
    { twitter = "https://twitter.com/johnofardeal" }
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"